### ISSUE TITLE
Expect Analysis Source Code Of Components Of k8s in public

### ISSUE THREAD

**Issue by tanjunchen** [Huang-Wei/k8s-for-beginners#2]
Sorry to bother you 
Such as Scheduler Controller  API-Server
Thanks !!!

**Comment by Huang-Wei** [comment]
That would be a good topic for advanced users of scheduler, but not for k8s beginners :)

**Comment by tanjunchen** [comment]
done.Thanks. if you have any plan about this , please tell me .:))
